pipeline {
    agent any

    stages {
        stage("Demo"){
            steps {
                myFunc("Hello from the other side")
            }
        }
    }
}

def myFunc(String myText) {

    echo "My text: ${myText}"
}