pipeline {
    agent any
    
    parameters {
        booleanParam(defaultValue: false, description: "Executar teste?", name: "teste")
    }
    
    stages {
        stage("Teste 1") {
            steps {
                script {
                    if(params.teste == false){
                        currentBuild.result = "SUCCESS"
                        return
                    }
                    else {
                        echo "Teste 1 foi marcado: ${params.teste}"
                    }
                }
            }
        }
    }
}